[
     "code" => 200,
     "body" => [
       "accounts_info" => null,
       "acquirer_reconciliation" => [],
       "additional_info" => [
         "authentication_code" => null,
         "available_balance" => null,
         "ip_address" => "190.3.50.57",
         "items" => [
           [
             "category_id" => null,
             "description" => null,
             "id" => null,
             "picture_url" => null,
             "quantity" => "1",
             "title" => "Nombre del plan",
             "unit_price" => "101",
           ],
         ],
         "nsu_processadora" => null,
       ],
       "authorization_code" => "006753",
       "binary_mode" => false,
       "brand_id" => null,
       "build_version" => "3.66.0-rc-2",
       "call_for_authorize_id" => null,
       "captured" => true,
       "card" => [
         "bin" => "442312",
         "cardholder" => [
           "identification" => [
             "number" => "30699254",
             "type" => "DNI",
           ],
           "name" => "gustavo enr bellino",
         ],
         "country" => "ARG",
         "date_created" => "2024-08-20T14:10:45.000-04:00",
         "date_last_updated" => "2024-08-20T14:10:45.000-04:00",
         "expiration_month" => 3,
         "expiration_year" => 2027,
         "first_six_digits" => "442312",
         "id" => "9142183404",
         "last_four_digits" => "9803",
         "tags" => [
           "invalid_card_art",
         ],
       ],
       "charges_details" => [
         [
           "accounts" => [
             "from" => "collector",
             "to" => "mp",
           ],
           "amounts" => [
             "original" => 7.69,
             "refunded" => 0,
           ],
           "client_id" => 0,
           "date_created" => "2024-08-20T14:10:45.000-04:00",
           "id" => "85481696557-001",
           "last_updated" => "2024-08-20T14:10:45.000-04:00",
           "metadata" => [
             "source" => "rule-engine",
           ],
           "name" => "mercadopago_fee",
           "refund_charges" => [],
           "reserve_id" => null,
           "type" => "fee",
         ],
         [
           "accounts" => [
             "from" => "collector",
             "to" => "mp",
           ],
           "amounts" => [
             "original" => 1.52,
             "refunded" => 0,
           ],
           "client_id" => 0,
           "date_created" => "2024-08-20T14:10:45.000-04:00",
           "id" => "85481696557-002",
           "last_updated" => "2024-08-20T14:10:45.000-04:00",
           "metadata" => [
             "mov_detail" => "tax_withholding_sirtac_sobretasa",
             "mov_financial_entity" => "cordoba",
             "mov_type" => "expense",
             "source" => "taxes",
             "tax_id" => 88696608041,
             "tax_status" => "applied",
             "user_id" => 165420174,
           ],
           "name" => "tax_withholding_sirtac_sobretasa-cordoba",
           "refund_charges" => [],
           "reserve_id" => null,
           "type" => "tax",
         ],
       ],
       "collector_id" => 165420174,
       "corporation_id" => null,
       "counter_currency" => null,
       "coupon_amount" => 0,
       "currency_id" => "ARS",
       "date_approved" => "2024-08-20T14:10:47.000-04:00",
       "date_created" => "2024-08-20T14:10:45.000-04:00",
       "date_last_updated" => "2024-08-20T14:10:50.000-04:00",
       "date_of_expiration" => null,
       "deduction_schema" => null,
       "description" => "Nombre del plan",
       "differential_pricing_id" => null,
       "external_reference" => "{"app":"walleq","plan_id":1}",
       "fee_details" => [
         [
           "amount" => 7.69,
           "fee_payer" => "collector",
           "type" => "mercadopago_fee",
         ],
       ],
       "financing_group" => null,
       "id" => 85481696557,
       "installments" => 1,
       "integrator_id" => null,
       "issuer_id" => "338",
       "live_mode" => true,
       "marketplace_owner" => null,
       "merchant_account_id" => null,
       "merchant_number" => null,
       "metadata" => [
         "preapproval_id" => "8ebeec1a99d242879f05a7725bd8cc52",
       ],
       "money_release_date" => "2024-08-20T14:10:47.000-04:00",
       "money_release_schema" => null,
       "money_release_status" => "released",
       "notification_url" => null,
       "operation_type" => "regular_payment",
       "order" => [],
       "payer" => [
         "email" => "gushbellino@gmail.com",
         "entity_type" => null,
         "first_name" => null,
         "id" => "90027827",
         "identification" => [
           "number" => "20306992547",
           "type" => "CUIT",
         ],
         "last_name" => null,
         "operator_id" => null,
         "phone" => [
           "number" => null,
           "extension" => null,
           "area_code" => null,
         ],
         "type" => null,
       ],
       "payment_method" => [
         "data" => [
           "routing_data" => [
             "merchant_account_id" => "1001",
           ],
         ],
         "id" => "visa",
         "issuer_id" => "338",
         "type" => "credit_card",
       ],
       "payment_method_id" => "visa",
       "payment_type_id" => "credit_card",
       "platform_id" => null,
       "point_of_interaction" => [
         "application_data" => [
           "name" => "recurring",
           "version" => "3.25.0-rc-1",
         ],
         "business_info" => [
           "branch" => "Merchant Services",
           "sub_unit" => "recurring",
           "unit" => "online_payments",
         ],
         "transaction_data" => [
           "billing_date" => "2024-08-20",
           "first_time_use" => true,
           "invoice_id" => "4881ace2a0844e6898980cead66679de",
           "invoice_period" => [
             "period" => 1,
             "type" => "monthly",
           ],
           "payment_reference" => null,
           "plan_id" => "1e84fc74dcd140f0b001eed4a1c7b99b",
           "processor" => null,
           "subscription_id" => "8ebeec1a99d242879f05a7725bd8cc52",
           "subscription_sequence" => [
             "number" => 1,
             "total" => null,
           ],
           "ticket_id" => "46718795434_3d7575767b6b3a76737f_A",
           "user_present" => null,
         ],
         "type" => "SUBSCRIPTIONS",
       ],
       "pos_id" => null,
       "processing_mode" => "aggregator",
       "refunds" => [],
       "release_info" => null,
       "shipping_amount" => 0,
       "sponsor_id" => null,
       "statement_descriptor" => "MERPAGO*KIOSQUITO",
       "status" => "approved",
       "status_detail" => "accredited",
       "store_id" => null,
       "tags" => null,
       "taxes_amount" => 0,
       "transaction_amount" => 101,
       "transaction_amount_refunded" => 0,
       "transaction_details" => [
         "acquirer_reference" => null,
         "external_resource_url" => null,
         "financial_institution" => null,
         "installment_amount" => 101,
         "net_received_amount" => 91.79,
         "overpaid_amount" => 0,
         "payable_deferral_period" => null,
         "payment_method_reference_id" => null,
         "total_paid_amount" => 101,
       ],
     ],
   ]